name: Update Deps
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 10 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.THM_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.THM_AUTOMATION_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.get_token.outputs.token }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - uses: markelliot/update-yarn-deps@v1
        with:
          primary-branch: main
          push-to-repo-token: ${{ steps.get_token.outputs.token }}
          commit-user: thm-automation[bot]
          commit-email: thm-automation[bot]@users.noreply.github.com
